# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a1151d3ed76d9fe3b2b2de887e11b7cceb6ee0fbf9c56e40636812c161d3cece13eae3f1b14058104678704294069d704ef557e46ec28956801a613ffddd293b

test:
  secret_key_base: 280f472f85e8820a7678a5893a4f601db7c01de9f6f6ba9d3154f0a4666b0e711bf4273eec4be5d24bbe469b5a96f4bda836338babad4085917e648145244533

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
